### ISSUE TITLE
2.0.3 datetime报错

### ISSUE THREAD

**Issue by lhyfree** [bluedazzle/django-simple-serializer#2]
datetime_time = datetime_time.astimezone(timezone.get_current_timezone())
ValueError: astimezone() cannot be applied to a naive datetime

=======================
2.0.2 是可以的，应该加上2.0.2 这句:
        if datetime_time.tzinfo is None:
            return datetime_time.strftime(time_format)

**Comment by bluedazzle** [comment]
感谢！修复 #1 的时候把这里逻辑改错了
