### ISSUE TITLE
关于FileField序列化的问题

### ISSUE THREAD

**Issue by fanmaoyu0871** [bluedazzle/django-simple-serializer#4]
你好，现在我的模型里面包含了一个FileField,我用它来上传图片的，但是经过序列化之后，得到的None，请问你那边有没有考虑这个情况？

**Comment by bluedazzle** [comment]
收到，这就修复~

**Comment by bluedazzle** [comment]
@fanmaoyu0871  收到，这就修复~

**Comment by bluedazzle** [comment]
@fanmaoyu0871 已修复 ，使用 pip install django-simple-serializer --upgrade 升级
